; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -O1 %s -o -

declare void @llvm.debugtrap()

define dso_local noundef i32 @_Z4testii(i32 noundef %a, i32 noundef %b) nounwind {
entry:
  %c = add i32 0, 0
  %cmp = icmp slt i32 %a, %c
  %foo = tail call noundef i32 @foo(i32 %c)
  br i1 %cmp, label %lt, label %end
lt:
  %cmp2 = icmp sgt i32 %b, %c
  %sel = select i1 %cmp2, i32 1, i32 0
  br i1 %cmp2, label %lt2, label %end

lt2:
  br label %end

end:
  %result = phi i32 [ %sel, %lt ], [ 0, %lt2 ], [ 0, %entry ]
  ret i32 %result
}

declare dso_local noundef i32 @foo() nounwind
declare dso_local noundef i32 @bar() nounwind

